### ISSUE TITLE
Wiimote does not pair

### ISSUE THREAD

**Issue by Minecraftplayer20** [epigramx/WiimoteHook#8]
When it started pairing it was pairing but then at the end it said no paired and connected wiimote found. I have retried multiple times but I still didn't get it working

**Comment by JuaniElias** [comment]
Have you connected it via Bluetooth to your PC first? You should do that from the Control Panel -> Devices and Printers -> Add a device. If you're on Windows 11 you need to View by: Large Icons and right click on Devices and Printers -> Open in new window You'll get the old menu so that no PIN is required. Then you can open WiimoteHook and it should connect

**Comment by Minecraftplayer20** [comment]
> Have you connected it via Bluetooth to your PC first? You should do that from the Control Panel -> Devices and Printers -> Add a device. If you're on Windows 11 you need to View by: Large Icons and right click on Devices and Printers -> Open in new window You'll get the old menu so that no PIN is required. Then you can open WiimoteHook and it should connect

Yes I have used control panel and when it was adding it, it was just stuck on saying connecting

**Comment by Trihy** [comment]
Some bt dongles have problems pairing wiimotes. They need specific driver.

For example TP-Link ub500 and some others based on that Realtek chipset. 

Most others works fine.
